version: "3"
services:
  frontend:
    container_name: code-editor-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
    - 3000:3000
    environment:
      # for hot reloading
      - CHOKIDAR_USEPOLLING=true